- name: Build container contrail-test-test {{ item }}
  command: |
    ./build-container.sh test \
    --tag {{ item }}-{{ contrail_container_tag }} \
    --registry-server {{ contrail_docker_registry }} \
    --sku {{ item }} \
    --contrail-repo {{ contrail_package_repository }} \
    --post
  become: true
  args:
    chdir: "{{ test_container_build_dir }}"
  tags:
    - skip_ansible_lint # ANSIBLE0013
