- name: Trigger Anamika jobs
  uri:
    url: http://anamika.englab.juniper.net:8080/job/start_sanity/buildWithParameters
    method: POST
    user: "{{ sanity_jenkins.user }}"
    password: "{{ sanity_jenkins.password }}"
    body: "TAG={{ item }}-{{ contrail_container_tag }}&\
           DOCKER_BUILD=1"
    follow_redirects: all
    force_basic_auth: yes
  with_items:
    - ocata
    - newton
  register: result
  retries: 5
  delay: 30
  until: result | success
  ignore_errors: true

- name: Get crumb from Zephyrine
  uri:
    url: http://zephyrine.englab.juniper.net:8080/crumbIssuer/api/xml?xpath=concat(//crumbRequestField,":",//crumb)
    method: GET
    user: "{{ sanity_jenkins.user }}"
    password: "{{ sanity_jenkins.password }}"
    follow_redirects: all
    force_basic_auth: true
    return_content: true
  register: crumb

- name: Prepare headers for Zephyrine
  set_fact:
    crumb_header: "{{ crumb_header | default({}) | combine({crumb.content.split(':')[0]: crumb.content.split(':')[1]}) }}"

- name: Trigger zephyrine jobs
  uri:
    url: http://zephyrine.englab.juniper.net:8080/job/start_sanity/buildWithParameters
    method: POST
    headers: "{{ crumb_header }}"
    user: "{{ sanity_jenkins.user }}"
    password: "{{ sanity_jenkins.password }}"
    body: "TAG={{ item }}-{{ contrail_container_tag }}&\
           DOCKER_BUILD=1"
    follow_redirects: all
    force_basic_auth: true
    status_code: 201
  with_items:
    - ocata
    - newton
