- name: Trigger full sanity jenkins job
  uri:
    url: "http://{{ item.0 }}:8080/job/start_sanity/buildWithParameters"
    method: POST
    user: "{{ sanity_jenkins.user }}"
    password: "{{ sanity_jenkins.password }}"
    body: "TAG={{ item.1 }}-{{ contrail_container_tag }}&\
           DOCKER_BUILD=1"
    follow_redirects: all
    force_basic_auth: yes
  with_cartesian:
    - "{{ sanity_jenkins_fqdn }}"
    - [ "ocata", "newton" ]
