- name: Trigger full sanity jenkins job
  uri:
    url: "http://{{ sanity_jenkins.fqdn }}:8080/job/{{ item.job_name }}/buildWithParameters"
    method: POST
    user: "{{ sanity_jenkins.user }}"
    password: "{{ sanity_jenkins.password }}"
    body: "TAG={{ item.tag_prefix }}-{{ build_number }}"
    follow_redirects: all
    force_basic_auth: yes
  with_items:
    - { job_name: "SVL_VT_Centos-7.4_Ocata_Ansible_master_Sanity", tag_prefix: "master-ocata" }
    - { job_name: "SVL_VT_Centos-7.4_k8s_ansible_master_Sanity", tag_prefix: "master-ocata" }
    - { job_name: "SVL_VT_Ubuntu-16.04.3_Newton_Helm_master_Sanity", tag_prefix: "master-newton" }
