- hosts: all
  pre_tasks:
    - name: Install build dependencies
      package:
        name: "{{ item }}"
        state: latest
      become: true
      with_items:
        - centos-release-openstack-ocata
    - name: Install build dependencies
      package:
        name: "{{ item }}"
        state: latest
      become: true
      with_items:
        - python2-requests
  roles:
    - role: contrail-ansible-deployer-dev
      cloud_orchestrator: openstack
      openstack_version: ocata
    - role: kolla-provision-dockers-dev
      kolla_provision_dir: '{{ ansible_env.HOME }}/src/{{ zuul.project.canonical_hostname }}/Juniper/contrail-kolla-ansible-dev'
      kolla_config_dir: "{{ kolla_provision_dir }}/etc/kolla"
      kolla_docker_distro: "ubuntu"
      openstack_version: "ocata"
      kolla_version: "4.0.0"
    - contrail-sanitytests-dev
